branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/npm"
  - path: "@semantic-release/github"
  - path: "@semantic-release/exec"
    prepareCmd: "export DOCKER_CONTENT_TRUST=1 && docker pull golang@sha256:2381c1e5f8350a901597d633b2e517775eeac7a6682be39225a93b22cfd0f8bb"
  - path: "@google/semantic-release-replace-plugin"
    replacements:
      - files:
          - "api/openapi-spec/v3/openapi.yaml"
        from: "version: 1.0.0"
        to: "version: ${nextRelease.version}"
        countMatches: true
        results:
          - file: "api/openapi-spec/v3/openapi.yaml"
            hasChanged: true
            numMatches: 1
            numReplacements: 1
  - path: "@semantic-release/exec"
    prepareCmd: "node_modules/.bin/swagger-cli bundle api/openapi-spec/v3/openapi.yaml --outfile openapi.pretty.json"
  - path: "@semantic-release/exec"
    prepareCmd: "node_modules/.bin/json5 openapi.pretty.json -o openapi.json"
  - path: "@semantic-release/exec"
    prepareCmd: "pnpm --stream -r build"
  - path: "@codedependant/semantic-release-docker"
    dockerProject: "timada0"
    dockerImage: "cobase"
  - path: "@semantic-release/git"
    assets:
      - "**/package.json"
      - package.json
