branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/npm"
  - path: "@semantic-release/github"
  - path: "@semantic-release/exec"
    prepareCmd: "export DOCKER_CONTENT_TRUST=1 && docker pull golang@sha256:2381c1e5f8350a901597d633b2e517775eeac7a6682be39225a93b22cfd0f8bb"
  # - path: "@semantic-release/exec"
  #   prepareCmd: "cargo run openapi -c configs/cobase.yml"
  - path: "@semantic-release/exec"
    prepareCmd: "pnpm --stream -r build"
  - path: "@codedependant/semantic-release-docker"
    dockerProject: "timada0"
    dockerImage: "cobase"
  - path: "@semantic-release/git"
    assets:
      - "**/package.json"
      - package.json
