branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - path: "@semantic-release/github"
  - "@timada/semantic-release-cargo"
  - path: "@semantic-release/exec"
    prepareCmd: "cargo update"
  - path: "@semantic-release/exec"
    prepareCmd: "cargo run openapi -c config/cobase.yml"
  - path: "@semantic-release/exec"
    prepareCmd: "cargo build --release"
  - path: "@codedependant/semantic-release-docker"
    dockerProject: "timada0"
    dockerImage: "cobase"
  - path: "@semantic-release/git"
    assets:
      - "**/Cargo.toml"
      - Cargo.lock
