branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/npm"
  - path: "@semantic-release/github"
  - "@timada/semantic-release-cargo"
  - path: "@semantic-release/exec"
    prepareCmd: "cargo update"
  - path: "@semantic-release/exec"
    prepareCmd: "cargo run openapi -c configs/cobase.yml"
  - path: "@semantic-release/exec"
    prepareCmd: "cargo build --release"
  - path: "@semantic-release/exec"
    prepareCmd: "pnpm --stream -r build"
  - path: "@codedependant/semantic-release-docker"
    dockerProject: "timada0"
    dockerImage: "cobase"
  - path: "@semantic-release/git"
    assets:
      - "**/Cargo.toml"
      - Cargo.lock
      - "**/package.json"
      - package.json
