version: '3.9'

services:
  cobase-cockroach-init:
    image: cockroachdb/cockroach:v22.1.10
    command: >
      sql --insecure --host="cockroach" --execute="
        CREATE DATABASE IF NOT EXISTS cobase;
        CREATE USER IF NOT EXISTS cobase; GRANT ALL ON DATABASE cobase TO cobase WITH GRANT OPTION;
      "
    restart: on-failure
    networks:
      - intranet

  cobase-migrate:
    image: timada0/cobase
    command: migrate -c /home/timada/cobase.yml
    volumes:
      - type: bind
        source: config/cobase.standalone.yml
        target: /home/timada/cobase.yml
    restart: on-failure
    profiles:
      - standalone
    networks:
      - intranet
    depends_on:
      - cobase-cockroach-init

  cobase:
    image: timada0/cobase
    ports:
      - 3011:80
    command: serve -c /home/timada/cobase.yml
    volumes:
      - type: bind
        source: config/cobase.standalone.yml
        target: /home/timada/cobase.yml
    profiles:
      - standalone
    restart: on-failure
    networks:
      - intranet
    depends_on:
      - cobase-migrate

networks:
  intranet:
    name: timada
    external: true
