version: '3.9'

services:
  cobase-cockroach-init:
    image: cockroachdb/cockroach:v22.2.5
    command: >
      sql --insecure --host="cockroach" --execute="
        CREATE DATABASE IF NOT EXISTS cobase;
        CREATE USER IF NOT EXISTS cobase; GRANT ALL ON DATABASE cobase TO cobase WITH GRANT OPTION;
        ALTER USER cobase CREATEDB;
      "
    restart: on-failure
    networks:
      - intranet

  cobase-migrate:
    image: timada0/cobase
    command: migrate -c /home/timada/cobase.yml
    volumes:
      - type: bind
        source: configs/standalone.yml
        target: /home/timada/cobase.yml
    restart: on-failure
    profiles:
      - standalone
    networks:
      - intranet
    depends_on:
      - cobase-cockroach-init

  cobase:
    image: timada0/cobase
    ports:
      - 3010:3010
      - 3011:3011
    volumes:
      - type: bind
        source: configs/standalone.yml
        target: /etc/cobase/config.yml
    profiles:
      - standalone
    restart: on-failure
    networks:
      - intranet
    depends_on:
      - cobase-migrate

  cobase-web:
    image: nginx:1.23-alpine
    volumes:
      - ./.docker/nginx/templates:/etc/nginx/templates
      - ./.docker/nginx/proxy.conf:/etc/nginx/proxy.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cobase-web.rule=Host(`cobase.timada.localhost`)"
      - "traefik.http.routers.cobase-web.tls=true"
      - "traefik.http.routers.cobase-web.entrypoints=https"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - intranet

networks:
  intranet:
    name: timada
    external: true
