version: '3.9'

services:
  cobase-cockroach-init:
    image: cockroachdb/cockroach:v22.1.10
    command: >
      sql --insecure --host="cockroach" --execute="
        CREATE DATABASE IF NOT EXISTS cobase;
        CREATE USER IF NOT EXISTS cobase; GRANT ALL ON DATABASE cobase TO cobase WITH GRANT OPTION;
      "
    restart: on-failure
    networks:
      - intranet

networks:
  intranet:
    name: timada
    external: true
