zone: eu-west-3a

addr:
  api: "0.0.0.0:3010"
  cluster: "0.0.0.0:3011"

log: debug

jwks:
  url: http://admin.oathkeeper.localhost:4456/.well-known/jwks.json

pikav:
  url: http://pikav.localhost:6751
  namespace: cobase

dsn: cockroach://cobase@127.0.0.1:26257/cobase?sslmode=disable

pulsar:
  url: pulsar://127.0.0.1:6650
  namespace: non-persistent://public/default

openapi:
  servers:
    - url: /cobase

swagger_ui:
  url: /cobase/openapi.json
