zone: eu-west-3
addr: ":3011"

log: debug

jwks:
  url: http://admin.oathkeeper.localhost:4456/.well-known/jwks.json

pikav:
  url: http://pikav.localhost:6750
  namespace: cobase

dsn: cockroach://cobase@127.0.0.1:26257/cobase?sslmode=disable

pulsar:
  url: pulsar://127.0.0.1:6650
  namespace: non-persistent://public/default
