zone: eu-west-3a

addr:
  api: "0.0.0.0:3010"
  cluster: "0.0.0.0:3011"

log: debug

public_folder: ./web/dist

jwks:
  url: http://admin.oathkeeper.localhost:4456/.well-known/jwks.json

pikav:
  url: http://pikav.localhost:6751
  namespace: cobase

dsn: cockroach://cobase@127.0.0.1:26257/cobase?sslmode=disable

openapi:
  servers:
    - url: /cobase

swagger_ui:
  url: /cobase/openapi.json

evento:
  delay: 0

storage:
  fs:
    root: /tmp
