zone: eu-west-3a

addr:
  api: "0.0.0.0:3010"
  cluster: "0.0.0.0:3011"

jwks:
  url: http://oathkeeper:4456/.well-known/jwks.json

pikav:
  url: http://pikav:6751
  namespace: cobase

dsn: cockroach://cobase@cockroach:26257/cobase?sslmode=disable

openapi:
  servers:
    - url: /api/cobase

swagger_ui:
  url: /api/cobase/openapi.json

evento:
  delay: 30

storage:
  fs:
    root: /tmp/cobase
