openapi: 3.0.0
info:
  version: 1.0.0
  title: Timada.co
  termsOfService: "https://timada.co/terms/"
  contact:
    email: contact@timada.co
    url: "https://timada.co/contact"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  description:
    $ref: ./info-description.md
tags:
  - name: User
    description: Operations about user api.
servers:
  - url: "https://timada.co/cobase/api"
paths:
  "/get-groups":
    $ref: "paths/get-groups.yaml"
  "/create-group":
    $ref: "paths/create-group.yaml"
components:
  schemas:
    Group:
      $ref: "components/schemas/Group.yaml"
    CommandResponse:
      $ref: "components/schemas/CommandResponse.yaml"
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
