openapi: 3.1.0
info:
  version: 1.0.0
  title: Timada.co
  termsOfService: 'https://timada.co/terms/'
  contact:
    email: contact@timada.co
    url: 'http://example.com/contact'
  license:
    name: GNU Affero General Public License v3
    identifier: AGPL-3.0
    url: 'https://opensource.org/licenses/AGPL-3.0'
  description:
    $ref: ./info-description.md
tags:
  - name: Public
    description: Operations about public api.
servers:
  - url: 'https://{tenant}/cobase/api'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://timada.co/cobase/api'
paths:
  '/groups':
    $ref: 'paths/groups.yaml'
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
