[package]
name = "cobase-api"
version = "0.3.4"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pikav-client = "0.12.1"
actix = "0.13.0"
actix-web = "4.3.0"
actix-files = "0.6.2"
nanoid = "0.4"
serde = "1.0.152"
serde_json = "1.0.91"
thiserror = "1.0.38"
tracing = "0.1.37"
actix-jwks = "0.1.1"
parse-display = "0.8.0"
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }
pulsar = "5.0.2"
futures = "0.3.26"
validator = { version = "0.16", features = ["derive"] }
evento = "0.2.7"
sqlx = { version = "0.6.2", features = ["runtime-actix-rustls", "postgres", "chrono", "uuid", "json", "offline"] }
utoipa = { version = "3.0.1", features = ["actix_extras", "uuid"] }
utoipa-swagger-ui = { version = "3.0.2", features = ["actix-web"] }

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde"
]
