[package]
name = "api"
version ="0.1.2"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pikav-client = "0.10.2"
actix = "0.13.0"
actix-web = "4.2.1"
nanoid = "0.4"
serde = "1.0.147"
serde_json = "1.0.87"
thiserror = "1.0.37"
tracing = "0.1.37"
actix-jwks = "0.1.1"
parse-display = "0.6"
tokio = { version = "1.21", features = ["rt-multi-thread", "macros"] }
pulsar = "4.1.3"
futures = "0.3.25"
validator = { version = "0.16", features = ["derive"] }
evento = "0.2.3"
sqlx = { version = "0.6", features = ["runtime-actix-rustls", "postgres", "chrono", "uuid", "json"] }
utoipa = { version = "2.3.0", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "2.0.1", features = ["actix-web"] }

[dependencies.uuid]
version = "1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde"
]

[dependencies.mongodb]
version = "2.3.1"
features = ["tokio-runtime"]
