name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  rust:
    uses: timada-org/.github/.github/workflows/rust-deploy.yml@v2
    with:
      image: timada0/cobase
    secrets:
      DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
