name: Release
on:
  push:
    branches:
      - main

jobs:
  rust:
    uses: timada-org/.github/.github/workflows/api-release.yml@v2.9.0
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
